"""
JSON Report Generator
======================
Exports scan session data to structured JSON.

Made by Monish Paramasivam
"""

from __future__ import annotations
import json
import logging
from pathlib import Path
from datetime import datetime

from ..models import ScanSession

logger = logging.getLogger(__name__)


class JSONReporter:
    """Generates machine-readable JSON reports from a ScanSession."""

    def __init__(self, output_dir: Path | str = Path(".")) -> None:
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        session: ScanSession,
        filename: str | None = None,
    ) -> Path:
        """Write session data to a JSON file and return the output path."""
        if not filename:
            ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
            filename = f"btaudit_report_{ts}.json"

        output_path = self.output_dir / filename
        payload = {
            "btaudit_report": {
                "schema_version": "1.0",
                "generated_at": datetime.utcnow().isoformat(),
                "author": "Monish Paramasivam",
                "legal_notice": (
                    "This report was generated by BTAudit for authorized "
                    "security assessment purposes only. Unauthorized use is prohibited."
                ),
            },
            **session.to_dict(),
        }

        output_path.write_text(
            json.dumps(payload, indent=2, default=str), encoding="utf-8"
        )
        logger.info("JSON report written to %s", output_path)
        return output_path

    def to_string(self, session: ScanSession) -> str:
        """Return the report as a JSON string (for piping / API use)."""
        return json.dumps(session.to_dict(), indent=2, default=str)
